EXP_GROUPS = {
        "MNIST":{"dataset":"mnist",
            "model":"mlp",
            "loss_func": {"name":"softmax_loss", "distance":False, "factor":1, "width":1e-3, "step": 60, "multiple": False},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-1, "regularization":0.001, "scheduler": True, "step": 20, "cycle": 60},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":800},
            
        "resnet32_lr1":{"dataset":"cifar10",
            "model":"resnet32",
            "loss_func": {"name":"softmax_loss", "distance":False, "factor":1, "width":1e-3, "step": 90, "multiple": True, "merge": True},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-1, "regularization":0.001, "scheduler": "step", "step": 50, "cycle": 150},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":900},
        
        "resnet32_lr1_distance":{"dataset":"cifar10",
            "model":"resnet32",
            "loss_func": {"name":"softmax_loss", "distance":True, "factor":1, "width":1e-3, "step": 90, "multiple": True, "merge": True},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-1, "regularization":0.001, "scheduler": "step", "step": 50, "cycle": 150},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":900},

        "mobileNetV2_ensemble":{"dataset":"cifar10",
            "model":"mobileNetV2",
            "loss_func": {"name":"softmax_loss", "distance":True, "factor":1, "width":1e-3, "step": 15, "multiple": True},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-2, "regularization":0.001, "scheduler": "step", "step": 5, "cycle":15},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":60},

        "mobileNetV2_f1_wide":{"dataset":"cifar10",
            "model":"mobileNetV2",
            "loss_func": {"name":"softmax_loss", "distance":True, "factor":1, "width":1e-3, "step": 90, "multiple": True},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-2, "regularization":0.001, "scheduler": "step", "step": 50, "cycle":150},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":900},

        "mobileNetV2_f2_wide":{"dataset":"cifar10",
            "model":"mobileNetV2",
            "loss_func": {"name":"softmax_loss", "distance":True, "factor":10, "width":1e-3, "step": 90, "multiple": True},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-2, "regularization":0.001, "scheduler": "step", "step": 50, "cycle":150},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":900},

        "mobileNetV2_f3_wide":{"dataset":"cifar10",
            "model":"mobileNetV2",
            "loss_func": {"name":"softmax_loss", "distance":True, "factor":100, "width":1e-3, "step": 90, "multiple": True},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-2, "regularization":0.001, "scheduler": "step", "step": 50, "cycle":150},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":900},

        "mobileNetV2_f2_cosine":{"dataset":"cifar10",
            "model":"mobileNetV2",
            "loss_func": {"name":"softmax_loss", "distance":True, "factor":10, "width":1e-3, "step": 90, "multiple": True},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-2, "regularization":0.001, "scheduler": "cosine", "step": 30, "cycle":90},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":900},

        "mobileNetV2_f3_cosine":{"dataset":"cifar10",
            "model":"mobileNetV2",
            "loss_func": {"name":"softmax_loss", "distance":True, "factor":100, "width":1e-3, "step": 90, "multiple": True},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-2, "regularization":0.001, "scheduler": "cosine", "step": 30, "cycle":90},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":900},

        "mobileNetV2_noreg_nodistance":{"dataset":"cifar10",
            "model":"mobileNetV2",
            "loss_func": {"name":"softmax_loss", "distance":False, "factor":1, "width":1e-3, "step": 90, "multiple": True},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-2, "regularization":0., "scheduler": "step", "step": 30, "cycle":90},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":450}
}

# rename step to cycle in loss_func

