EXP_GROUPS = {
        "MNIST":{"dataset":"mnist",
            "model":"mlp",
            "loss_func": {"name":"softmax_loss", "distance":False, "factor":1, "width":1e-3, "step": 60, "multiple": False},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-1, "regularization":0.001, "scheduler": True, "step": 20, "cycle": 60},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":800},
            
        "resnet32_merge_long":{"dataset":"cifar10",
            "model":"resnet32",
            "loss_func": {"name":"softmax_loss", "distance":True, "factor":1, "width":1e-3, "step": 90, "multiple": True, "merge": True},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-2, "regularization":0.001, "scheduler": "step", "step": 30, "cycle": 90},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":900},

        "mobileNetV2_merge_long":{"dataset":"cifar10",
            "model":"mobileNetV2",
            "loss_func": {"name":"softmax_loss", "distance":True, "factor":1, "width":1e-3, "step": 90, "multiple": True, "merge": True},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-2, "regularization":0.001, "scheduler": "step", "step": 30, "cycle":90},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":900},

        "mobileNetV2_merge_f2":{"dataset":"cifar10",
            "model":"mobileNetV2",
            "loss_func": {"name":"softmax_loss", "distance":True, "factor":10, "width":1e-3, "step": 90, "multiple": True, "merge": True},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-2, "regularization":0.001, "scheduler": "step", "step": 30, "cycle":90},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":450},

        "mobileNetV2_f2":{"dataset":"cifar10",
            "model":"mobileNetV2",
            "loss_func": {"name":"softmax_loss", "distance":True, "factor":10, "width":1e-3, "step": 90, "multiple": True},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-2, "regularization":0.001, "scheduler": "step", "step": 30, "cycle":90},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":900},

        "mobileNetV2_noreg":{"dataset":"cifar10",
            "model":"mobileNetV2",
            "loss_func": {"name":"softmax_loss", "distance":True, "factor":1, "width":1e-3, "step": 90, "multiple": True},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-2, "regularization":0., "scheduler": "step", "step": 30, "cycle":90},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":450},

        "mobileNetV2_reg2":{"dataset":"cifar10",
            "model":"mobileNetV2",
            "loss_func": {"name":"softmax_loss", "distance":True, "factor":1, "width":1e-3, "step": 90, "multiple": True},
            "optimizer":{"name":"sgd_momentum_wdecay", "lr":1e-2, "regularization":0.01, "scheduler": "step", "step": 30, "cycle":90},
            "acc_func":{"name":"softmax_accuracy"},
            "batch_size":128,
            "max_epochs":450}
}

